{{
	config(
		materialized='incremental',
		unique_key='ITEM_ID'
	)
}}
SELECT DISTINCT SI.ID AS ITEM_ID, SI.Name AS ITEM_NAME, SC.Name AS CATEGORY_NAME, LATFLAITEM.PRICING_TYPE AS PRICING_TYPE, SI.VISIBILITY AS VISIBILITY, SI.TYPE AS TYPE, LATFLAITEM.VAT_RATE AS VAT_RATE   
FROM PC_STITCH_DB.SQUAREBI.SQUARE_ITEMS SI
LEFT JOIN PC_STITCH_DB.SQUAREBI.SQUARE_CATEGORIES SC
ON SI.CATEGORY_ID = SC.ID
LEFT JOIN (
    SELECT DISTINCT ID, f.value:pricing_type::string AS PRICING_TYPE, fl.value:rate::float AS VAT_RATE
     from PC_STITCH_DB.SQUAREBI.SQUARE_ITEMS
  , lateral flatten( input => VARIATIONS ) f
  , lateral flatten( input => FEES ) fl
  ) LATFLAITEM ON SI.ID = LATFLAITEM.ID
 

