{{
	config(
		materialized='incremental',
		unique_key='SHIP_TO_PARTY'
	)
}}
 SELECT DISTINCT CUSTOMER_HIERACHY AS LOCATION_ID,CUSTOMER_HIERACHY_DESCRIPTION AS LOCATION_NAME, BILL_TO_PARTY AS CUSTOMER_ACCOUNT_NUMBER, BILL_TO_PARTY_DESCRIPTION AS CUSTOMER_DESCRIPTION, SHIP_TO_PARTY, SHIP_TO_PARTY_NAME, CASE WHEN BILL_TO_PARTY_DESCRIPTION LIKE '%Web%' THEN 'Online' WHEN BILL_TO_PARTY_DESCRIPTION = 'Homebase Head Office - Vendor 41849' THEN 'HB' WHEN BILL_TO_PARTY_DESCRIPTION LIKE '%Homebase:%' THEN 'Store' WHEN BILL_TO_PARTY_DESCRIPTION LIKE '%Fired Earth Ltd%' THEN 'Fired Earth' WHEN BILL_TO_PARTY_DESCRIPTION LIKE '%NEXT Retail%' THEN 'Next' WHEN BILL_TO_PARTY_DESCRIPTION LIKE '%B & Q PLC%' THEN 'B & Q' WHEN BILL_TO_PARTY_DESCRIPTION LIKE '%Colorificio Centrale%' THEN 'Colorificio' ELSE 'Other' END AS "CHANNEL", MAX(POSTCODE) AS POSTCODE
	FROM CRAIG_ROSE.PUBLIC.BILLING_STG BI 
    GROUP BY CUSTOMER_HIERACHY, CUSTOMER_HIERACHY_DESCRIPTION, BILL_TO_PARTY, BILL_TO_PARTY_DESCRIPTION, SHIP_TO_PARTY, SHIP_TO_PARTY_NAME
 
 

