{{
	config(
		materialized='incremental',
		unique_key='DISCOUNT_ID'
	)
}}
SELECT DISTINCT SD.ID AS DISCOUNT_ID, SD.AMOUNT_MONEY:amount::NUMBER AS DISCOUNT_AMOUNT, SD.DISCOUNT_TYPE AS DISCOUNT_TYPE, SD.NAME AS DISCOUNT_NAME, SD.RATE AS DISCOUNT_RATE
	FROM PC_STITCH_DB.SQUAREBI.SQUARE_DISCOUNTS SD

