{{
	config(
		materialized='incremental',
		unique_key='LOCATION_ID'
	)
}}
SELECT DISTINCT ID AS LOCATION_ID, NAME AS LOCATION_NAME, BUSINESS_NAME, BUSINESS_ADDRESS:address_line_1 AS BUSINESS_ADDRESS_LINE_1, BUSINESS_ADDRESS:locality AS BUSINESS_CITY, BUSINESS_ADDRESS:postal_code AS BUSINESS_POST_CODE, BUSINESS_TYPE  
	FROM PC_STITCH_DB.SQUAREBI.SQUARE_LOCATION

