{{
	config(
		materialized='incremental',
		unique_key='SHIP_TO_PARTY'
	)
}}
 SELECT DISTINCT CUSTOMER_HIERACHY,CUSTOMER_HIERACHY_DESCRIPTION, BILL_TO_PARTY, BILL_TO_PARTY_DESCRIPTION, SHIP_TO_PARTY, SHIP_TO_PARTY_NAME, CITY ,CASE WHEN BILL_TO_PARTY_DESCRIPTION LIKE '%Web%' THEN 'Online' WHEN BILL_TO_PARTY_DESCRIPTION = 'Homebase Head Office - Vendor 41849' THEN 'HB' WHEN BILL_TO_PARTY_DESCRIPTION LIKE '%Homebase:%' THEN 'Store' WHEN BILL_TO_PARTY_DESCRIPTION LIKE '%Fired Earth Ltd%' THEN 'Fired Earth' WHEN BILL_TO_PARTY_DESCRIPTION LIKE '%NEXT Retail%' THEN 'Next' WHEN BILL_TO_PARTY_DESCRIPTION LIKE '%B & Q PLC%' THEN 'B & Q' WHEN BILL_TO_PARTY_DESCRIPTION LIKE '%Colorificio Centrale%' THEN 'Colorificio' ELSE 'Other' END AS "CHANNEL", MAX(POSTCODE) AS POSTCODE, 
CASE WHEN SALES_REP_CODE = 'DH' THEN 'David Higham' WHEN SALES_REP_CODE = 'VP' THEN 'Victoria Porteous' WHEN SALES_REP_CODE = 'PM' THEN 'Peter Munday' WHEN SALES_REP_CODE = 'ST' THEN 'Sam Turner' WHEN SALES_REP_CODE = 'DH' THEN 'Dan Henson' WHEN SALES_REP_CODE = 'HS' THEN 'Hema Sherratt'  WHEN SALES_REP_CODE = 'SG' THEN 'Simon Gander' WHEN SALES_REP_CODE = 'EB' THEN 'Edward Brown'  END AS "ACCOUNT_MANAGER", CASE WHEN SALES_REP_CODE = 'DH' THEN 'Active' ELSE NULL END AS "STORE_STATUS"
	FROM CRAIG_ROSE.PUBLIC.BILLING_STG BI 
    GROUP BY CUSTOMER_HIERACHY, CUSTOMER_HIERACHY_DESCRIPTION, BILL_TO_PARTY, BILL_TO_PARTY_DESCRIPTION, SHIP_TO_PARTY, SHIP_TO_PARTY_NAME, CITY, SALES_REP_CODE
 
 

