{{
	config(
		materialized='incremental',
		unique_key='SHIP_TO_PARTY'
	)
}}
SELECT DISTINCT CUSTOMER_HIERACHY AS LOCATION_ID,CUSTOMER_HIERACHY_DESCRIPTION AS LOCATION_NAME, BILL_TO_PARTY AS CUSTOMER_ACCOUNT_NUMBER, BILL_TO_PARTY_DESCRIPTION AS CUSTOMER_DESCRIPTION, SHIP_TO_PARTY, SHIP_TO_PARTY_NAME, CASE WHEN CUSTOMER_DESCRIPTION LIKE '%Web%' THEN 'Online' WHEN CUSTOMER_DESCRIPTION = 'Homebase Head Office - Vendor 41849' THEN 'HB' WHEN CUSTOMER_DESCRIPTION LIKE '%Homebase:%' THEN 'Store' WHEN CUSTOMER_DESCRIPTION LIKE '%Fired Earth Ltd%' THEN 'Fired Earth' WHEN CUSTOMER_DESCRIPTION LIKE '%NEXT Retail%' THEN 'Next' WHEN CUSTOMER_DESCRIPTION LIKE '%B & Q PLC%' THEN 'B & Q' WHEN CUSTOMER_DESCRIPTION LIKE '%Colorificio Centrale%' THEN 'Colorificio' ELSE 'Other' END AS "CHANNEL", POSTCODE
	FROM BILLING_STG

