{{
	config(
		materialized='incremental',
		unique_key='EMPLOYEE_ID'
	)
}}
SELECT SE.ID AS EMPLOYEE_ID, SE.FIRST_NAME AS EMPLOYEE_FIRST_NAME, SE.LAST_NAME AS EMPLOYEE_LAST_NAME, SE.EMAIL AS EMPLOYEE_EMAIL, SE.CREATED_AT AS EMPLOYEE_CREATED_AT
	FROM PC_STITCH_DB.SQUAREBI.SQUARE_EMPLOYEES SE	

