{{
	config(
		materialized='incremental',
		unique_key='BILLING_DOCUMENT'
	)
}}
SELECT DISTINCT BI.CUSTOMER_HIERACHY AS location_id, to_date(regexp_replace(DATE_FOR_INVOICE_BILLING_INDEX_AND_PRINTOUT,'"','',1), 'YYYYMMDD') AS date_of_transaction, MAX(BI.MATERIAL) AS  item_id, BILLING_DOCUMENT, BILLING_ITEM , SHIP_TO_PARTY_NAME, SHIP_TO_PARTY, CUSTOMER_PURCHASE_ORDER AS PO_Number, DISTRIBUTION_CHANNEL, NAME_OF_PERSON_WHO_CREATED_THE_OBJECT AS ORDER_CREATED_BY, SALES_DOCUMENT AS INVOICE_NUMBER, DOCUMENT_CURRENCY AS BILLING_CURRENCY, BILLING_QUANTITY_IN_SALES_UNITS AS QUANTITY_IN_UNITS, BILLING_QUANTITY_IN_QUS AS QUANTITY_IN_LITRES, SALES_UNIT, COST_IN_DOCUMENT_CURRENCY AS COST_OF_GOODS, BI.NET_VALUE_OF_THE_BILLING_ITEM_IN_DOCUMENT_CURRENCY AS VALUE_AMOUNT, TAX_AMOUNT_IN_DOCUMENT_CURRENCY__ST AS VAT, SALES_REP_CODE AS ACC_MANAGER,  to_date(regexp_replace(CREATED,'"','',1), 'YYYYMMDD') AS DATE_CREATED
	FROM BILLING_STG BI
	
	{% if is_incremental() %}
	WHERE DATE_CREATED > (select max(DATE_CREATED) from {{ this }})
{% endif %}
	
    GROUP BY BI.CUSTOMER_HIERACHY, date_of_transaction, BI.NET_VALUE_OF_THE_BILLING_ITEM_IN_DOCUMENT_CURRENCY, BILLING_DOCUMENT, BILLING_ITEM, SHIP_TO_PARTY, SHIP_TO_PARTY_NAME, CUSTOMER_PURCHASE_ORDER, DISTRIBUTION_CHANNEL, NAME_OF_PERSON_WHO_CREATED_THE_OBJECT, SALES_DOCUMENT, DOCUMENT_CURRENCY, BILLING_QUANTITY_IN_SALES_UNITS, BILLING_QUANTITY_IN_QUS, SALES_UNIT, COST_IN_DOCUMENT_CURRENCY, TAX_AMOUNT_IN_DOCUMENT_CURRENCY__ST, SALES_REP_CODE, DATE_CREATED
	
